# COMP3400/6981 Assignment 1

**Name:** *Type your name here*

**MUN id:** *Type your name here*

The dataset you will be using in this assignment was downloaded from Kaggle (https://www.kaggle.com/datasets/cashncarry/fifa-23-complete-player-dataset) and contains data about players in FIFA 23 (A Soccer/Football video game developed by Electronic Arts(EA)). 

For a better understanding of the dataset, please read the information available at the URL and explore the dataset in this notebook. From here on out we will refer to the sport as soccer, to avoid any confusion. There's no in-depth description of the features, but most of them are intuitive. Here is a description created by the instructional staff for your reference for the columns we will be using through this assignment. 

**ID:** Player's unique identifier.

**Name:** Player's abbreviated name.

**FullName:** Player's full name.

**Age:** Player's age.

**Height:** Player's height.

**Weight:** Player's weight.

**Nationality:** Player's nationality.

**Overall:** Player's overall statistics regarding their abilities.

**Potential:** Player's potential. 

**Growth:** Player's growth.

**BestPosition:** Position in the field that a player generally plays.

**Club:** The Club that the player plays for. 

**ValueEUR:** Value in Euro of the player.

**WageEUR:** Wage of the player in Euro.

Note this dataset was last updated in January, so information may be outdated or incorrect. 
Use the following two cells to make sure you are loading the dataset correctly.

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('players_fifa23.csv')
df

,ID,Name,FullName,Age,Height,Weight,PhotoUrl,Nationality,Overall,Potential,...,LMRating,CMRating,RMRating,LWBRating,CDMRating,RWBRating,LBRating,CBRating,RBRating,GKRating
0,165153,K. Benzema,Karim Benzema,34,185,81,https://cdn.sofifa.net/players/165/153/23_60.png,France,91,91,...,89,84,89,67,67,67,63,58,63,21
1,158023,L. Messi,Lionel Messi,35,169,67,https://cdn.sofifa.net/players/158/023/23_60.png,Argentina,91,91,...,91,88,91,67,66,67,62,53,62,22
2,231747,K. Mbappé,Kylian Mbappé,23,182,73,https://cdn.sofifa.net/players/231/747/23_60.png,France,91,95,...,92,84,92,70,66,70,66,57,66,21
3,192985,K. De Bruyne,Kevin De Bruyne,31,181,70,https://cdn.sofifa.net/players/192/985/23_60.png,Belgium,91,91,...,91,91,91,82,82,82,78,72,78,24
4,188545,R. Lewandowski,Robert Lewandowski,33,185,81,https://cdn.sofifa.net/players/188/545/23_60.png,Poland,91,91,...,86,83,86,67,69,67,64,63,64,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18355,261899,Chen Keqiang,Keqiang Chen,22,183,70,https://cdn.sofifa.net/players/261/899/23_60.png,China PR,48,54,...,49,50,49,51,52,51,52,52,52,19
18356,271152,M. Furaih,Mohammed Furaih,22,162,60,https://cdn.sofifa.net/players/271/152/23_60.png,Saudi Arabia,48,57,...,50,45,50,39,36,39,37,29,37,17
18357,269578,Ning Hao,Hao Ning,37,175,70,https://cdn.sofifa.net/players/269/578/23_60.png,China PR,48,48,...,48,48,48,47,47,47,46,43,46,18
18358,269577,Feng Zeyuan,Zeyuan Feng,20,181,70,https://cdn.sofifa.net/players/269/577/23_60.png,China PR,48,58,...,47,42,47,36,33,36,35,31,35,15
18359,259649,E. Singh,Engson Singh,19,169,62,https://cdn.sofifa.net/players/259/649/23_60.png,India,48,63,...,49,49,49,44,43,44,43,39,43,14

In [2]:
df.describe()

,ID,Age,Height,Weight,Overall,Potential,Growth,TotalStats,BaseStats,ValueEUR,...,LMRating,CMRating,RMRating,LWBRating,CDMRating,RWBRating,LBRating,CBRating,RBRating,GKRating
count,18360.000000,18360.000000,18360.000000,18360.000000,18360.000000,18360.000000,18360.000000,18360.000000,18360.000000,1.836000e+04,...,18360.000000,18360.000000,18360.000000,18360.000000,18360.000000,18360.000000,18360.000000,18360.000000,18360.000000,18360.000000
mean,236693.153704,25.303540,181.526089,75.139869,65.832680,70.959532,5.126852,1602.493682,357.932026,2.881407e+06,...,58.476906,57.388508,58.476906,56.292266,55.931917,56.292266,55.657789,54.534423,55.657789,23.193900
std,26493.482449,4.693175,6.857984,6.998178,6.802402,6.171324,5.312458,272.296129,39.700131,7.679217e+06,...,13.940940,13.138632,13.940940,13.854138,13.841226,13.854138,14.108821,14.708686,14.108821,15.059682
min,1179.000000,16.000000,155.000000,49.000000,48.000000,48.000000,0.000000,759.000000,224.000000,0.000000e+00,...,18.000000,18.000000,18.000000,17.000000,19.000000,17.000000,17.000000,18.000000,17.000000,10.000000
25%,221466.250000,22.000000,177.000000,70.000000,62.000000,67.000000,0.000000,1470.000000,331.000000,4.750000e+05,...,54.000000,53.000000,54.000000,51.000000,48.000000,51.000000,49.000000,45.000000,49.000000,17.000000
50%,240997.000000,25.000000,182.000000,75.000000,66.000000,71.000000,4.000000,1640.000000,358.000000,9.750000e+05,...,62.000000,60.000000,62.000000,59.000000,59.000000,59.000000,59.000000,58.000000,59.000000,18.000000
75%,258527.250000,29.000000,186.000000,80.000000,70.000000,75.000000,9.000000,1785.000000,385.000000,2.000000e+06,...,67.000000,66.000000,67.000000,66.000000,66.000000,66.000000,65.000000,66.000000,65.000000,20.000000
max,271341.000000,44.000000,206.000000,105.000000,91.000000,95.000000,26.000000,2312.000000,502.000000,1.905000e+08,...,92.000000,91.000000,92.000000,88.000000,89.000000,88.000000,87.000000,90.000000,87.000000,90.000000

## Task 1 - Removing and Creating columns (15 marks)

For this task you need to show that you can handle simple pre-processing steps such as removing and creating new attributes in your dataframe. The tasks you must perform in this unit are listed below. 

1. Remove all columns to the right of WageEUR as we won't use them in this assignment.
2. Remove *Total Stats, BaseStats, Positions*, and *PhotoUrl*
3. Add An additional column labeled as GMValue (General Manager Value), that computes the following equation: $ 'Overall' * 0.9 + 'Growth'$, where overall and growth are columns present in your dataframe.
4. Add two other columns, one for first name (label it as FirstName), and one for last name (label it as LastName). 
5. Finally, sort your dataframe using GMValue in descending order

**Tip:** Print your dataframe in the end of this task and make sure it has 17 columns (this includes the three new ones created in this task).

In [2]:
# Type your answers here #
# You may use multiple cells, but make sure you show the # 
# last configuration of your dataframe for proper assessment #

## Task 2 - Aggregating and Summarizing information (30 marks)

In the this task, we are interested in discovering several things about the players described in the dataset. Please write your queries in the cells below and answer them in this section.
 
1. Who are the top 5 best soccer players (i.e., use attribute *Overall* to determine the best player)?

    **Answer:** *--- Please type your answer here ---*


2. Who are the top 5 best soccer players under the age of 25?

    **Answer:** *--- Please type your answer here ---*


3. Who is the tallest player?

    **Answer:** *--- Please type your answer here ---*


4. Who is the best player from Canada and what team does he play for? 
    
    **Answer:** *--- Please type your answer here ---*

In [3]:
# Type your answers here #
# You may use multiple cells, but make sure you answer # 
# the questions using the cell above #

## Task 3 - Evaluating groups of players (30 marks)

For task 3, we are interested in subgroups of players, rather than individuals.

1. What are the 5 nations with the highest average overall score and that at least 50 players are listed in the dataset?

    **Answer:** *--- Please type your answer here ---*


2. Which 5 clubs are paying the highest total wage to their players?

    **Answer:** *--- Please type your answer here ---*


3. What is the average potential and average overall score for each group age younger than 19 (including 19 years old players)? Could you find any trend? Please discuss 

    **Answer:** *--- Please type your answer here ---*

In [4]:
# Type your answers here #
# You may use multiple cells, but make sure you answer # 
# the questions using the cell above #

## Task 4 - Simple plots (25 marks)

1. Create a scatter plot for players from Canada with the x axis as *Overall* and the y axis as *WageEUR*. By looking at this plot, could you identify some type of relation between the overall attribute and the player's wage? 

**Answer:** *--- Please type your answer here ---*


2. Create a bar chart for the average wage per position (use Best Position for a players position). By looking at this plot, what is the position that you would choose to play if you are looking to have the highest probability of having a high wage? 

**Answer:** *--- Please type your answer here ---*

3. Plot a line chart with the x axis as age, and the y axis as the average GMValue. Include only ages 18 to 30. How would you interpret the relation between these two attributes?

**Answer:** *--- Please type your answer here ---*

In [5]:
# Type your answers here #
# You may use multiple cells, but make sure you answer # 
# the questions using the cell above #

## (Graduate students only) - Task 5 - Using plots to answer questions (30 marks)

**Yes, the total marks for graduate students sums to 130 marks and only if you get all of those you will be scoring 100% in this assignment**

For all plots below, we are only considering players from England, Germany, Spain, and Argentina (can be retrieved by column *country*).
Make sure you include the appropriate axis labels, title, and legend if required.

### Plot 1

1. Create two box plots side by side.

    a. The first should have all the player data with the x axis being the region the player is from. 
    
    b. The second should be a boxplot with the top 5% and bottom 5% of players removed from the dataset (From the 5th-95th percentile). You can use the quantile function to do this. 
    

2. Which country had the best change in overall mean, and which country the worst? Why would these changes occur? (Please include a few sentences)

**Answer:** *--- Please type your answer here ---*

In [6]:
# Type your answers here #
# You may use multiple cells, but make sure you answer # 
# the questions using the cell above #

### Plot 2

In this task, we are interested if certain countries are better at producing different kinds of players. For this exercise, we are not interested in the goal keeper. The X axis of your charts should be the Nationality of the player, and the bars should be split by position for each nationality. You can assume that players only play the position defined under BestPosition. You can ignore additional positions that are not defined below.

1. The first plot must be a grouped bar chart for Forwards for each Country. Positions (LW, ST, RW).

**Answer:** *--- Please type your answer here ---*


2. The second is a grouped bar chart for Midfielders. Positions (LM, RM, CM)

**Answer:** *--- Please type your answer here ---*


3. The third plot is a grouped bar chart for Defenders. Positions (LB, RB, CB)

**Answer:** *--- Please type your answer here ---*


4. The fourth plot is a grouped bar chart except instead of grouping by position, we will group by forwards, midfielders, and defenders. 

**Answer:** *--- Please type your answer here ---*

In [7]:
# Type your answers here #
# You may use multiple cells, but make sure you answer # 
# the questions using the cell above #